# Scientific and Engineering Summary of Aviation Basics (AERO 1111)

**1. Basic Principles of Flight and Aerodynamics:**
- Lighter-than-air machines (like hot air balloons/airships) rely on Archimedes' law of buoyancy, which states that the buoyant force on a submerged object equals the weight of the fluid it displaces.
- Upward motion in an airship occurs when the density of the internal gas decreases so that the upward thrust exceeds the weight. To descend, helium is released. The flight direction is controlled by a rudder independent of wind.
- Heavier-than-air aerodynamic machines (airplanes and helicopters) rely on aerodynamic forces to generate Lift via thrust and forward speed.
- Propellers generate thrust by moving a very large mass of air at a relatively low velocity.
- Jet Engines generate thrust by moving a small mass of gas at a very high velocity.
- Turbofan engines are favored in commercial aviation for their high efficiency, providing a smaller change in velocity to a larger mass flow rate.

**2. Flow Variables and Regimes:**
- The key variables that define air/fluid flow are: Density (ρ), Viscosity (μ), Pressure (P), Temperature (T), and Velocity (v).
- Flow types are classified as: viscous vs. inviscid, compressible vs. incompressible, steady vs. unsteady, laminar vs. turbulent, and single-phase vs. multiphase.
- Compressibility effects cannot be ignored when an aircraft exceeds a Mach number of 0.3, or when density changes by more than 5% due to pressure variations. Assuming incompressibility at high speeds leads to inaccurate aerodynamic results.
- Flight regimes are classified by Mach number (M): Subsonic (M < 1), Transonic (0.8 < M < 1.2), Sonic (M = 1), Supersonic (1.2 < M < 5), and Hypersonic (M > 5).

**3. Shock Waves and Wing Design:**
- When an aircraft exceeds the speed of sound, it produces shock waves that carry significant energy, resulting in a Sonic Boom originating from the front and tail of the plane.
- To delay or reduce Wave Drag during high-speed flights, aircraft use Swept Wings. This design ensures that the velocity component normal to the leading edge remains subsonic even if the aircraft is supersonic.
- Delta Wings are used to provide root thickness for structural strength, larger fuel storage space, and occasionally to omit the horizontal stabilizer.
- Transonic Area Rule: Drag is related to the rate of change in the cross-sectional area from nose to tail (wave drag is related to the secondary derivative of the volume distribution). Smoother area progression minimizes drag.

**4. Primary Forces and The Airfoil:**
- In stable flight, four main forces act on the aircraft: Lift (upwards), Weight (downwards due to gravity), Thrust (forwards), and Drag (backwards, opposing motion).
- Lift is generated by the pressure difference around an airfoil. According to the motion effect, faster airflow over the cambered (curved) upper surface creates lower relative pressure, sucking the wing upwards.
- Drag is the aerodynamic force component parallel to the direction of motion, whereas Lift is perpendicular to it.
- The Angle of Attack (AOA) and camber shape significantly affect lift characteristics.

**5. Earth's Atmosphere & Standard Models:**
- The layers of the atmosphere are: Troposphere, Stratosphere, Mesosphere, Thermosphere, and Exosphere.
- Aeronautical engineers primarily focus on the Troposphere and Stratosphere, as these contain the relevant pressure, temperature, and density variations for standard aircraft.
- The International Standard Atmosphere (ISA) is a hypothetical model used universally by aerospace vehicles to provide a common reference for design, performance determination, and simulation.

**6. Aviation Industry and Safety Regulations:**
- Civil Aviation is heavily regulated by authorities like ICAO (UN level), EASA (Europe), and CAA (UK) which mandate specific operational, technical, and navigation log documents for every flight.
- Economically, the airline scheduling environment is highly complex due to unionized labor, unpredictable disruptions, high fixed costs, and the fact that a flight seat is a perishable commodity that cannot be stored.
- Future Aviation Technologies are increasingly looking at Electric and Hybrid aircraft concepts to achieve net-zero carbon emissions by 2050. 
- The primary hurdle for large electric aircraft is the low power density and high weight of current batteries, prompting hybrid solutions for take-off and landing phases.

**7. Human Factors and Accident Rates:**
- Human error dominates as the cause of aviation accidents, accounting for roughly 70% of fatal hull loss accidents.
- Controlled Flight into Terrain (CFIT) and Loss of Control are the most significant causes of fatal events. A majority of aviation accidents occur during the Landing and Take-off phases rather than cruise.
- The SHEL Model (Software, Hardware, Environment, Liveware) is used to contextualize human interaction and manage stress, teamwork, and decision-making limitations.
- Aeronautical Decision-Making (ADM) aims to replace hazardous behavioral attitudes (like Anti-authority, Impulsivity, Invulnerability, Macho, and Resignation) with rational antidotes.

---

### Formulas and Physical Laws (With Units and Usage)

**1. Engine Thrust and Power Formulas**
*   **Thrust Produced:** `Thrust = Q × V`
*   **Power Required:** `Power = 0.5 × Q × V²`
*   **Units:** Thrust [N], Power [W], Q (Mass flow rate) [kg/s], V (Slipstream velocity) [m/s].
*   **Usage:** Used to find static thrust and mechanical power required based on the mass of expelled air and velocity.

**2. Mach Number Ratio**
*   **Law:** `M = V / a`
*   **Units:** M [No unit], V (Aircraft Velocity) [m/s], a (Speed of Sound) [m/s].
*   **Usage:** Determines the compressibility regime of an aircraft relative to the local air medium. 

**3. Speed of Sound in a Medium (a)**
*   **Law:** `a = √(γ · R · T)`
*   **Units:** a [m/s], T (Absolute Temperature) [K], R (Gas Constant = 287 J/kg·K for air), γ (Ratio of specific heats = 1.4 for air).
*   **Usage:** Calculates the exact speed of sound at a given cruising altitude since ambient temperature dictates sound wave velocity.

**4. Mach Cone Angle (Shock Wave Angle)**
*   **Law:** `sin(µ) = 1 / M`
*   **Units:** µ (Mach angle) [Degrees], M (Mach number) [Unitless & > 1].
*   **Usage:** Analyzes the geometric structure of a sonic boom's transmission towards the ground relative to the flight path.

**5. Lift and Drag Coefficients**
*   **Lift Coefficient:** `C_L = Lift / (0.5 × ρ × V² × S)`
*   **Drag Coefficient:** `C_D = Drag / (0.5 × ρ × V² × S)`
*   **Units:** C_L and C_D [No unit], Lift / Drag [N], ρ (Air Density) [kg/m³], V (Velocity) [m/s], S (Wing Area) [m²].
*   **Usage:** Empirical equations applied in wind tunnel test environments to determine how geometric shapes affect lifting capabilities and drag penalties.

---

### Solved Examples and Exercises

**Exercise 1: Basic Mach Number Calculation**
*   **Problem:** An aircraft is flying at a speed of 370 m/s at an altitude where the speed of sound is 320 m/s. Calculate the Mach number.
*   **Solution Steps:**
    1. Apply the Mach number formula: `M = V / a`.
    2. Substitute the given values: `M = 370 / 320`.
    3. `M = 1.156 ≈ 1.16`.

**Exercise 2: Supersonic Flight Speed and Ambient Temperature**
*   **Problem:** A supersonic fighter aircraft is flying at an altitude of 5,000 m with a speed of 570 m/s. The air temperature is -17.3 °C at 5,000 m. Find the speed of sound in the air and the aircraft's Mach number.
*   **Solution Steps:**
    1. Find the Absolute Temperature (K): `T = 273.15 + (-17.3) = 255.85 K` (rounded to 255.7 K in text).
    2. Calculate Speed of Sound (a): `a = √(γ·R·T) = √(1.41 × 287 × 255.7) = 320.5 m/s`. *(Note: Using γ=1.41 as per standard problem constants)*.
    3. Calculate Mach Number (M): `M = V / a = 570 / 320.5 = 1.78`.

**Exercise 3: Bullet Velocity from Mach Angle**
*   **Problem:** Determine the velocity of a bullet fired in the air if the Mach angle is observed to be 30°. The temperature of the air is 22 °C. (Take γ = 1.4 and R = 287.43 J/kg·K).
*   **Solution Steps:**
    1. Find Absolute Temperature: `T = 22 + 273 = 295 K`.
    2. Calculate Speed of Sound (a): `a = √(1.4 × 287.43 × 295) = √118709 ≈ 345 m/s`.
    3. Find the Mach Number (M) using the Mach Cone formula: `sin(30°) = 1 / M` ➔ `0.5 = 1 / M` ➔ `M = 2`.
    4. Calculate Bullet Velocity (V): `V = M × a = 2 × 345 = 690 m/s`. *(Note: 690 m/s was implied as the final step).*

**Exercise 4: Distance Traveled during Sonic Boom Delay**
*   **Problem:** A sonic boom is heard 20.5 s after the Concorde passes overhead. Assuming Mach 1.75 and a speed of sound of 320 m/s, calculate the distance traveled by the flight during this time.
*   **Solution Steps:**
    1. Calculate Aircraft Speed (V): `V = M × a = 1.75 × 320 = 560 m/s`.
    2. Calculate Distance (d) using time delay (t = 20.5 s): `d = V × t = 560 × 20.5 = 11,480 m = 11.48 km`.

**Exercise 5: Altitude from a Delayed Sonic Boom**
*   **Problem:** An aircraft is flying horizontally at Mach 1.8 over a flat desert. A sonic boom is heard on the ground 8.1 s after the aircraft passed directly overhead. Assume the speed of sound is 350 m/s. What altitude is the aircraft flying at?
*   **Solution Steps:**
    1. Calculate Aircraft Speed (V): `V = M × a = 1.8 × 350 = 630 m/s`.
    2. Calculate Horizontal Distance traveled in 8.1 s: `x = V × t = 630 × 8.1 = 5,103 m`.
    3. Determine the Mach Angle (µ) from `sin(µ) = 1 / M`: `sin(µ) = 1 / 1.8` ➔ `µ ≈ 33.7°`. This makes `tan(µ) ≈ 0.666`.
    4. Calculate Altitude (h) using right-triangle geometry: `h = x × tan(µ) = 5,103 × 0.666 = 3,400 m`.

**Exercise 6: Observer Boom Delay Time Calculation**
*   **Problem:** A supersonic fighter moves with Mach 1.5 at an altitude of 500 m. What is the time lapsed before the acoustic disturbance reaches an observer on the ground after being directly overhead? Given T = 20 °C, γ = 1.4, R = 287 J/kg·K.
*   **Solution Steps:**
    1. Find Absolute Temperature: `T = 20 + 273 = 293 K`.
    2. Find Speed of Sound (a): `a = √(1.4 × 287 × 293) ≈ 343 m/s`.
    3. Find Aircraft Speed (V): `V = M × a = 1.5 × 343 = 515 m/s`.
    4. Find Mach Angle (µ): `sin(µ) = 1 / 1.5` ➔ `µ = 41.8°`, so `tan(µ) ≈ 0.894`.
    5. Find Time Delay (t): Based on geometry, `tan(µ) = h / (V × t)`. Rearranging gives `t = h / (V × tan(µ)) = 500 / (515 × 0.894) ≈ 1.09 s`.

**Exercise 7: Lift Coefficient of an Aircraft**
*   **Problem:** Determine the lift coefficient of a B787-8 with a mass of 200,000 kg cruising at a speed of 900 km/hr at an altitude of 12 km, where the density is 0.3105 kg/m³. The wing reference area is 377 m².
*   **Solution Steps:**
    1. Find the Lift force (L) needed to balance the weight (W = M × g): `L = W = 200,000 × 9.81 = 1.962 × 10^6 N`.
    2. Convert cruise speed (V) to m/s: `V = 900 × (1000 / 3600) = 250 m/s`.
    3. Apply the Lift Coefficient formula: `C_L = L / (0.5 × ρ × V² × S)`.
    4. Substitute the values: `C_L = (1.962 × 10^6) / (0.5 × 0.3105 × 250² × 377) = 0.5263`.

**Exercise 8: Drag Force During Cruise**
*   **Problem:** Wind tunnel tests of a B787-8 model indicate that the drag coefficient is given by the expression: `C_D = 0.018 + 0.036 C_L²`. Given the cruise conditions from the previous exercise, determine the drag force.
*   **Solution Steps:**
    1. Calculate the Drag Coefficient (C_D) substituting C_L = 0.5263: `C_D = 0.018 + (0.036 × 0.5263²) = 0.02797`.
    2. Apply the Drag Force formula: `Drag = C_D × 0.5 × ρ × V² × S`.
    3. Substitute the values: `Drag = 0.02797 × 0.5 × 0.3105 × 250² × 377 = 102,316 N = 102 kN`.
